apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kxsc1whap-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/kxsc1whap-dotnet-basic-gitops